In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

### List revisited

In [3]:
l_1d = list(range(1, 11))

In [4]:
l_1d

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
l_2d = []
for i in range(1, 11):
    l = list()
    for j in range(1, 4):
        l.append(i**j)
        
    l_2d.append(l)

In [6]:
l_2d

[[1, 1, 1],
 [2, 4, 8],
 [3, 9, 27],
 [4, 16, 64],
 [5, 25, 125],
 [6, 36, 216],
 [7, 49, 343],
 [8, 64, 512],
 [9, 81, 729],
 [10, 100, 1000]]

In [7]:
# 2d list with list comprehension
l_2d = [[i**j for j in range(1, 4)] for i in range(1, 11)]

In [8]:
l = list(range(1, 11))
l.append("football")
l.append("$")
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 'football', '$']

### List vs numpy array

In [9]:
arr = np.arange(20)
l = list(range(20))

In [10]:
type(arr)

numpy.ndarray

In [11]:
type(l)

list

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [14]:
import time

In [15]:
start  = time.time()
l = np.arange(200000000)
end = time.time()
print(end - start)

0.4996674060821533


In [16]:
# Time taken by numpy array and loop
%time for i in range(20): arr1 = arr*3 

CPU times: total: 0 ns
Wall time: 0 ns


In [18]:
# %time for i in range(20): l1 = [x*3 for x in l]

In [20]:
# Creating a numpy array from list
l_1d = [1,2,3,4]
arr_1d = np.array(l_1d)

In [21]:
arr_1d

array([1, 2, 3, 4])

In [23]:
#l_2d = [[1,2], [3,4], ["abc", "def"]]
#arr_2d = np.array(l_2d, dtype=int)

In [25]:
#arr_2d

### Some numpy functions

In [26]:
arr = np.arange(10)


In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
type(arr)

numpy.ndarray

In [29]:
arr.shape

(10,)

In [30]:
arr.ndim

1

In [31]:
arr.size

10

In [32]:
arr.dtype

dtype('int32')

In [33]:
float_arr = arr.astype(np.float64)
float_arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.isnan(float_arr)

array([False, False, False, False, False, False, False, False, False,
       False])

In [36]:
float_arr[[2, 5, 6]] = np.nan
float_arr

array([ 0.,  1., nan,  3.,  4., nan, nan,  7.,  8.,  9.])

In [37]:
np.isnan(float_arr)

array([False, False,  True, False, False,  True,  True, False, False,
       False])

In [38]:
# Get all the nan values
float_arr[~np.isnan(float_arr)]

array([0., 1., 3., 4., 7., 8., 9.])

In [39]:
# Get all not nan values 
float_arr[~np.isnan(float_arr)]
# float_arr.astype(np.int)

array([0., 1., 3., 4., 7., 8., 9.])

In [40]:
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [41]:
# Creating array of ones
# np.ones(2, dtype=int)
np.ones((2,3), dtype = int) 

array([[1, 1, 1],
       [1, 1, 1]])

In [42]:
# Creating array of zeros
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [43]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [44]:
# Diagonal elements 1 
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [45]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [46]:
# Empty array
# Optional C parameter with C style or Fortran style \
# Default value of float
np.empty(5)

array([0., 0., 0., 0., 0.])

In [47]:
# Reshaping the shape of array
arr_1d = np.arange(1, 21) # 1d 
arr_2d = arr_1d.reshape((5,4))
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [48]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
arr_2d.ndim

2

### Random module and numpy array

In [50]:
# Alias for random_sample 
# [0.0, 1.0) Half open interval 
np.random.random()

0.4366702711848943

In [51]:
np.random.random(size=5)

array([0.83062939, 0.37754387, 0.77690261, 0.87844762, 0.4355504 ])

In [52]:
np.random.random(size=(5,3))

array([[0.60727732, 0.26427138, 0.49805509],
       [0.31840245, 0.80264761, 0.01867472],
       [0.25698279, 0.92390939, 0.72692798],
       [0.53292484, 0.34152112, 0.06795856],
       [0.7792377 , 0.17364874, 0.40097665]])

In [53]:
# Closed interval [0,1]
np.random.rand(5)

array([0.70980646, 0.89360719, 0.12017389, 0.23536315, 0.29307703])

In [54]:
np.random.rand(4,3)

array([[0.60825284, 0.62171351, 0.19728495],
       [0.27198625, 0.70241529, 0.21691938],
       [0.21720041, 0.79496282, 0.48886219],
       [0.76797623, 0.09429307, 0.56752865]])

In [55]:
# Standard normal distribution (mean of 0 and std of 1)
np.random.randn(3)

array([-0.56836148, -0.01100995, -1.20908792])

In [56]:
np.random.randn(4,3,)

array([[-2.79155487,  1.13729204, -1.02879098],
       [ 0.15868089,  1.47225552,  0.5184859 ],
       [ 0.46744074, -0.15290651, -0.93203407],
       [-1.30067715,  0.28494545, -0.79794769]])

In [57]:
# Number between half open interval
np.random.randint(5, 1000)

108

In [58]:
np.random.randint(5, 1000, size=10)

array([763, 224, 857, 329, 431, 734, 594, 219, 135, 927])

In [59]:
# Replace = True allows repetition while false provides unique elements
# Another thing for replace to be false the samples should be less or equal to population
np.random.choice([5, 6, 9, 10]) 

6

### Numpy Arithmetic

In [60]:
l = list(range(1, 10))

In [61]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
l + [2]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 2]

In [64]:
# List cannot be broadcasterd 
# List not applicable for numerical computation
#l + 2

In [65]:
# Broadcasting demo 
arr = np.arange(1,5)
arr + 2

array([3, 4, 5, 6])

In [66]:
arr*3 

array([ 3,  6,  9, 12])

In [67]:
arr1 = np.array([[1,3,5], [2,4,6]])
arr2 = np.array([4, 7, 9])

In [68]:
arr1 + arr2

array([[ 5, 10, 14],
       [ 6, 11, 15]])

In [71]:
#arr1 + np.array([4,7])

In [72]:
arr1 * arr2

array([[ 4, 21, 45],
       [ 8, 28, 54]])

In [73]:
arr2 - arr1

array([[3, 4, 4],
       [2, 3, 3]])

In [74]:
arr1 / arr2

array([[0.25      , 0.42857143, 0.55555556],
       [0.5       , 0.57142857, 0.66666667]])

In [75]:
arr1 % arr2

array([[1, 3, 5],
       [2, 4, 6]])

### Indexing and Slicing

In [76]:
arr = np.array([11, 19, 23, 29, 37, 65, 89, 102, 234, 589, 876])

In [77]:
arr

array([ 11,  19,  23,  29,  37,  65,  89, 102, 234, 589, 876])

In [78]:
arr[4]

37

In [79]:
arr[4:8]

array([ 37,  65,  89, 102])

In [80]:
arr[::-1]

array([876, 589, 234, 102,  89,  65,  37,  29,  23,  19,  11])

In [81]:
arr[::-2]

array([876, 234,  89,  37,  23,  11])

In [82]:
arr[:]

array([ 11,  19,  23,  29,  37,  65,  89, 102, 234, 589, 876])

In [83]:
arr[::]

array([ 11,  19,  23,  29,  37,  65,  89, 102, 234, 589, 876])

In [84]:
arr[3:]

array([ 29,  37,  65,  89, 102, 234, 589, 876])

In [85]:
arr[:3]

array([11, 19, 23])

In [86]:
arr[-1]

876

In [87]:
arr

array([ 11,  19,  23,  29,  37,  65,  89, 102, 234, 589, 876])

In [88]:
arr[1:8:2]

array([ 19,  29,  65, 102])

In [89]:
arr

array([ 11,  19,  23,  29,  37,  65,  89, 102, 234, 589, 876])

In [90]:
# Array slices are the views, any change will affect the original array
arr[5:] = 101

In [91]:
arr

array([ 11,  19,  23,  29,  37, 101, 101, 101, 101, 101, 101])

In [92]:
# Use .copy() if you want the original as it is 
arr_copy = arr[:3].copy()
arr_copy = 20
arr

array([ 11,  19,  23,  29,  37, 101, 101, 101, 101, 101, 101])

In [93]:
arr_copy

20

In [94]:
arr_2d = np.arange(1, 21).reshape(4,5)

In [95]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [96]:
arr_2d[1:3, 2:4]

array([[ 8,  9],
       [13, 14]])

In [97]:
arr_2d[3]

array([16, 17, 18, 19, 20])

In [98]:
arr_2d[:, :3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [99]:
arr_2d[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Boolean Indexing

In [100]:
arr = np.arange(1, 11)
arr[arr == 2]

array([2])

In [101]:
arr > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [102]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
arr_2d = np.arange(1, 21).reshape(4, 5)
arr_2d < 15

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False]])

In [104]:
arr_2d[arr_2d > 15]

array([16, 17, 18, 19, 20])

### Dot product

In [105]:
a = np.arange(1, 4)
b = np.array([4, -5, 6])

In [106]:
np.dot(a, b)

12

In [107]:
a @ b

12

In [108]:
a.dot(b)

12

In [109]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1,5], [-1, 6], [4, 9]])

In [110]:
a @ b

array([[ 11,  44],
       [ 23, 104]])

### Transpose 

In [111]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [113]:
x = np.arange(1, 11).T
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Maximum,minimum and sum

In [114]:
a = np.array([[1, 2, 3], [4, 5, 6]])


In [115]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
a.max()

6

In [117]:
a.max(axis=1) # Maximum values of columns

array([3, 6])

In [118]:
a.max(axis=0) # Maximum values of rows 

array([4, 5, 6])

In [119]:
a.min(axis=1) # Minimum values of columns

array([1, 4])

In [120]:
a.sum(axis=1)

array([ 6, 15])

In [121]:
a.sum(axis=1)

array([ 6, 15])

In [122]:
a.sum(axis=0)

array([5, 7, 9])

In [123]:
a.mean()

3.5

In [124]:
a.mean(axis=1)

array([2., 5.])

### Reducing dimension to one 

In [125]:
arr = np.arange(1, 21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [126]:
arr.ndim

2

In [127]:
# Ravel returns view any change will affect the original array
arr_cpy =  arr.copy()

In [128]:
bla

NameError: name 'bla' is not defined

In [129]:
bla[4] = 500

NameError: name 'bla' is not defined

In [130]:
bla

NameError: name 'bla' is not defined

In [131]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [132]:
# Flatten returns a copy, original array won't be affected
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Concatenation

In [133]:
a = np.array([[1,3,5],[2,4,6]])
b = np.array([[7,9,11],[8,10,12]])

In [134]:
np.concatenate([a,b])

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [ 7,  9, 11],
       [ 8, 10, 12]])

In [135]:
np.concatenate([a,b], axis=1)

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [136]:
np.hstack((a,b))

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [137]:
np.vstack((a,b))

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [ 7,  9, 11],
       [ 8, 10, 12]])